version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tides-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
s3_prefix = "tides-api"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.build]
[default.build.parameters]
cached = true
parallel = true
